/**
 * Un ejemplo que modela un Linea usando POO
 *
 * @author (Milton Jesús Vera Contreras - miltonjesusvc@ufps.edu.co)
 * @version 0.000000000000001 :) --> Math.sin(Math.PI-Double.MIN_VALUE)
 */
class FrmLinea
/** Creates new form FrmLinea  */
(private val linea: Linea) : javax.swing.JFrame() {
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private var cmdAyuda: javax.swing.JButton? = null
    private var cmdDeterminarUbicacion: javax.swing.JButton? = null
    private var cmdModificarLinea: javax.swing.JButton? = null
    private var jLabel2: javax.swing.JLabel? = null
    private var lblImagen: javax.swing.JLabel? = null
    private var lblX1: javax.swing.JLabel? = null
    private var lblX2: javax.swing.JLabel? = null
    private var lblY1: javax.swing.JLabel? = null
    private var lblY2: javax.swing.JLabel? = null
    private var paneDatos: javax.swing.JPanel? = null
    private var panelAdorno: javax.swing.JPanel? = null
    private var panelBotones: javax.swing.JPanel? = null
    private var panelTitulo: javax.swing.JPanel? = null
    private var txtX1: javax.swing.JTextField? = null
    private var txtX2: javax.swing.JTextField? = null
    private var txtY1: javax.swing.JTextField? = null
    private var txtY2: javax.swing.JTextField? = null

    init {
        initComponents()
        setVisible(true)
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private fun initComponents() {

        panelTitulo = javax.swing.JPanel()
        jLabel2 = javax.swing.JLabel()
        panelAdorno = javax.swing.JPanel()
        lblImagen = javax.swing.JLabel()
        panelBotones = javax.swing.JPanel()
        cmdModificarLinea = javax.swing.JButton()
        cmdDeterminarUbicacion = javax.swing.JButton()
        cmdAyuda = javax.swing.JButton()
        paneDatos = javax.swing.JPanel()
        lblX1 = javax.swing.JLabel()
        txtX1 = javax.swing.JTextField()
        lblY1 = javax.swing.JLabel()
        txtY1 = javax.swing.JTextField()
        lblX2 = javax.swing.JLabel()
        txtX2 = javax.swing.JTextField()
        lblY2 = javax.swing.JLabel()
        txtY2 = javax.swing.JTextField()

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE)
        setTitle("Linea en Plano Cartesiano")
        setResizable(false)

        panelTitulo!!.setBorder(javax.swing.BorderFactory.createTitledBorder(""))
        panelTitulo!!.setLayout(java.awt.BorderLayout())

        jLabel2!!.setFont(java.awt.Font("DejaVu Sans", 0, 36))
        jLabel2!!.setText("Linea en Plano Cartesiano")
        panelTitulo!!.add(jLabel2, java.awt.BorderLayout.CENTER)

        getContentPane().add(panelTitulo, java.awt.BorderLayout.NORTH)

        panelAdorno!!.setBorder(javax.swing.BorderFactory.createTitledBorder(""))

        lblImagen!!.setFont(java.awt.Font("DejaVu Sans", 1, 13))
        lblImagen!!.setForeground(java.awt.Color(0, 0, 255))
        lblImagen!!.setHorizontalAlignment(javax.swing.SwingConstants.LEFT)
        lblImagen!!.setIcon(javax.swing.ImageIcon(getClass().getResource("/descartes+caricatura.jpg"))) // NOI18N
        lblImagen!!.setText("Ubicación Desconocida")
        lblImagen!!.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER)
        lblImagen!!.setVerticalTextPosition(javax.swing.SwingConstants.TOP)
        panelAdorno!!.add(lblImagen)

        getContentPane().add(panelAdorno, java.awt.BorderLayout.EAST)

        panelBotones!!.setBorder(javax.swing.BorderFactory.createTitledBorder(""))
        panelBotones!!.setLayout(java.awt.GridLayout(1, 3))

        cmdModificarLinea!!.setText("Actualizar Coordenadas")
        cmdModificarLinea!!.addActionListener(object : java.awt.event.ActionListener() {
            fun actionPerformed(evt: java.awt.event.ActionEvent) {
                cmdModificarLineaActionPerformed(evt)
            }
        })
        panelBotones!!.add(cmdModificarLinea)

        cmdDeterminarUbicacion!!.setText("Determinar Ubicación")
        cmdDeterminarUbicacion!!.addActionListener(object : java.awt.event.ActionListener() {
            fun actionPerformed(evt: java.awt.event.ActionEvent) {
                cmdDeterminarUbicacionActionPerformed(evt)
            }
        })
        panelBotones!!.add(cmdDeterminarUbicacion)

        cmdAyuda!!.setText("Ayuda")
        cmdAyuda!!.addActionListener(object : java.awt.event.ActionListener() {
            fun actionPerformed(evt: java.awt.event.ActionEvent) {
                cmdAyudaActionPerformed(evt)
            }
        })
        panelBotones!!.add(cmdAyuda)

        getContentPane().add(panelBotones, java.awt.BorderLayout.SOUTH)

        paneDatos!!.setBorder(javax.swing.BorderFactory.createTitledBorder(""))
        paneDatos!!.setLayout(java.awt.GridLayout(4, 2))

        lblX1!!.setText("X Punto 1:")
        lblX1!!.setBorder(null)
        paneDatos!!.add(lblX1)

        txtX1!!.setFont(java.awt.Font("DejaVu Sans", 0, 18))
        txtX1!!.setHorizontalAlignment(javax.swing.JTextField.CENTER)
        txtX1!!.setText("0.0")
        txtX1!!.setBorder(javax.swing.BorderFactory.createEtchedBorder())
        paneDatos!!.add(txtX1)

        lblY1!!.setText("Y Punto 1:")
        lblY1!!.setBorder(null)
        paneDatos!!.add(lblY1)

        txtY1!!.setFont(java.awt.Font("DejaVu Sans", 0, 18))
        txtY1!!.setHorizontalAlignment(javax.swing.JTextField.CENTER)
        txtY1!!.setText("0.0")
        txtY1!!.setBorder(javax.swing.BorderFactory.createEtchedBorder())
        paneDatos!!.add(txtY1)

        lblX2!!.setText("X Punto 2:")
        lblX2!!.setBorder(null)
        paneDatos!!.add(lblX2)

        txtX2!!.setFont(java.awt.Font("DejaVu Sans", 0, 18))
        txtX2!!.setHorizontalAlignment(javax.swing.JTextField.CENTER)
        txtX2!!.setText("0.0")
        txtX2!!.setBorder(javax.swing.BorderFactory.createEtchedBorder())
        paneDatos!!.add(txtX2)

        lblY2!!.setText("Y Punto 2:")
        lblY2!!.setBorder(null)
        paneDatos!!.add(lblY2)

        txtY2!!.setFont(java.awt.Font("DejaVu Sans", 0, 18))
        txtY2!!.setHorizontalAlignment(javax.swing.JTextField.CENTER)
        txtY2!!.setText("0.0")
        txtY2!!.setBorder(javax.swing.BorderFactory.createEtchedBorder())
        paneDatos!!.add(txtY2)

        getContentPane().add(paneDatos, java.awt.BorderLayout.CENTER)

        pack()
    }// </editor-fold>//GEN-END:initComponents

    private fun cmdDeterminarUbicacionActionPerformed(evt: java.awt.event.ActionEvent) {//GEN-FIRST:event_cmdDeterminarUbicacionActionPerformed
        lblImagen!!.setText(linea.getUbicacion())
    }//GEN-LAST:event_cmdDeterminarUbicacionActionPerformed

    private fun cmdModificarLineaActionPerformed(evt: java.awt.event.ActionEvent) {//GEN-FIRST:event_cmdModificarLineaActionPerformed
        linea.setX1(Float.parseFloat(txtX1!!.getText()))
        linea.setY1(Float.parseFloat(txtY1!!.getText()))
        linea.setX2(Float.parseFloat(txtX2!!.getText()))
        linea.setY2(Float.parseFloat(txtY2!!.getText()))
        lblImagen!!.setText("Ubicación Desconocida")
        javax.swing.JOptionPane.showMessageDialog(this, "Coordenadas Actualizadas")
    }//GEN-LAST:event_cmdModificarLineaActionPerformed

    private fun cmdAyudaActionPerformed(evt: java.awt.event.ActionEvent) {//GEN-FIRST:event_cmdAyudaActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Determina el la ubicación de la Linea respecto al plano.")
    }//GEN-LAST:event_cmdAyudaActionPerformed
    // End of variables declaration//GEN-END:variables
}
